In [1]:
!cd

C:\Users\admin\Desktop\2021-K-Digital-Training-main\SQL


In [4]:
import pandas as pd

In [7]:
import numpy as np

In [5]:
import pymysql.cursors

In [54]:
connection = pymysql.connect(host='localhost',
        user='root',
        password='1281',
        db='classicmodels',
        charset='utf8',
        cursorclass=pymysql.cursors.DictCursor)
sql = 'select customers.customerNumber, customers.salesRepEmployeeNumber, payments.checkNumber from customers LEFT JOIN payments on customers.customerNumber = payments.customerNumber;'
try:
    with connection.cursor() as cursor:
        cursor.execute(sql)
        result = cursor.fetchone()
#         result = cursor.fetchall()
        print(result)
finally:
    connection.close()

{'customerNumber': 125, 'salesRepEmployeeNumber': None, 'checkNumber': None}


In [32]:
# MySQl DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost', user='root',
                       password='1281', db='classicmodels', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
sql = 'select customers.customerNumber, customers.salesRepEmployeeNumber, payments.checkNumber from customers LEFT JOIN payments on customers.customerNumber = payments.customerNumber;'

try:
    with conn.cursor() as curs:
        curs.execute(sql)
        rs = curs.fetchall()        
        # DB에서 받아온 값을 DataFrame에 넣음
        df = pd.DataFrame(rs)
        print(df)
        
        # df.to_svv('query.csv')
finally:
    conn.close()

     customerNumber  salesRepEmployeeNumber checkNumber
0               125                     NaN        None
1               169                     NaN        None
2               206                     NaN        None
3               223                     NaN        None
4               237                     NaN        None
..              ...                     ...         ...
292             458                  1702.0    DD995006
293             458                  1702.0    NA377824
294             458                  1702.0    OO606861
295             484                  1702.0    GK294076
296             484                  1702.0    JH546765

[297 rows x 3 columns]


In [33]:
df.isnull().sum()

customerNumber             0
salesRepEmployeeNumber    22
checkNumber               24
dtype: int64

In [45]:
df.values

array([[125, nan, None],
       [169, nan, None],
       [206, nan, None],
       [223, nan, None],
       [237, nan, None],
       [247, nan, None],
       [273, nan, None],
       [293, nan, None],
       [303, nan, None],
       [307, nan, None],
       [335, nan, None],
       [348, nan, None],
       [356, nan, None],
       [361, nan, None],
       [369, nan, None],
       [409, nan, None],
       [443, nan, None],
       [459, nan, None],
       [465, nan, None],
       [477, nan, None],
       [480, nan, None],
       [481, nan, None],
       [124, 1165.0, 'AE215433'],
       [124, 1165.0, 'BG255406'],
       [124, 1165.0, 'CQ287967'],
       [124, 1165.0, 'ET64396'],
       [124, 1165.0, 'HI366474'],
       [124, 1165.0, 'HR86578'],
       [124, 1165.0, 'KI131716'],
       [124, 1165.0, 'LF217299'],
       [124, 1165.0, 'NT141748'],
       [129, 1165.0, 'DM826140'],
       [129, 1165.0, 'ID449593'],
       [129, 1165.0, 'PI42991'],
       [161, 1165.0, 'BR352384'],
       [161

In [43]:
data = df.values
data
# ix = [i for in range(data.shape[1] if i !=3)]

array([[125, nan, None],
       [169, nan, None],
       [206, nan, None],
       [223, nan, None],
       [237, nan, None],
       [247, nan, None],
       [273, nan, None],
       [293, nan, None],
       [303, nan, None],
       [307, nan, None],
       [335, nan, None],
       [348, nan, None],
       [356, nan, None],
       [361, nan, None],
       [369, nan, None],
       [409, nan, None],
       [443, nan, None],
       [459, nan, None],
       [465, nan, None],
       [477, nan, None],
       [480, nan, None],
       [481, nan, None],
       [124, 1165.0, 'AE215433'],
       [124, 1165.0, 'BG255406'],
       [124, 1165.0, 'CQ287967'],
       [124, 1165.0, 'ET64396'],
       [124, 1165.0, 'HI366474'],
       [124, 1165.0, 'HR86578'],
       [124, 1165.0, 'KI131716'],
       [124, 1165.0, 'LF217299'],
       [124, 1165.0, 'NT141748'],
       [129, 1165.0, 'DM826140'],
       [129, 1165.0, 'ID449593'],
       [129, 1165.0, 'PI42991'],
       [161, 1165.0, 'BR352384'],
       [161

In [48]:
# shape[0], shape[1]를 이용하여 전체 행의 갯수와 열의 갯수를 반환받을 수 있다.
ix = [i for i in range(data.shape[1]) if i !=3]
ix

[0, 1, 2]

In [50]:
# data 대신 df.values로 넣어도 되는지 테스트해봄(고아름)
# ix = [i for i in range(df.values.shape[1]) if i !=3]
# ix

[0, 1, 2]

In [84]:
X = data[:,:2]
X

array([[125, nan],
       [169, nan],
       [206, nan],
       [223, nan],
       [237, nan],
       [247, nan],
       [273, nan],
       [293, nan],
       [303, nan],
       [307, nan],
       [335, nan],
       [348, nan],
       [356, nan],
       [361, nan],
       [369, nan],
       [409, nan],
       [443, nan],
       [459, nan],
       [465, nan],
       [477, nan],
       [480, nan],
       [481, nan],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [124, 1165.0],
       [129, 1165.0],
       [129, 1165.0],
       [129, 1165.0],
       [161, 1165.0],
       [161, 1165.0],
       [161, 1165.0],
       [161, 1165.0],
       [321, 1165.0],
       [321, 1165.0],
       [450, 1165.0],
       [487, 1165.0],
       [487, 1165.0],
       [112, 1166.0],
       [112, 1166.0],
       [112, 1166.0],
       [205, 1166.0],
       [205, 1166.0],
       [20

In [85]:
from sklearn.impute import SimpleImputer

In [86]:
imputer = SimpleImputer(strategy='mean')

# fit on the dataset
imputer.fit(X)

# transform the dataset
Xtrans = imputer.transform(X)

In [74]:
Xtrans

array([[ 125.        , 1393.93454545],
       [ 169.        , 1393.93454545],
       [ 206.        , 1393.93454545],
       [ 223.        , 1393.93454545],
       [ 237.        , 1393.93454545],
       [ 247.        , 1393.93454545],
       [ 273.        , 1393.93454545],
       [ 293.        , 1393.93454545],
       [ 303.        , 1393.93454545],
       [ 307.        , 1393.93454545],
       [ 335.        , 1393.93454545],
       [ 348.        , 1393.93454545],
       [ 356.        , 1393.93454545],
       [ 361.        , 1393.93454545],
       [ 369.        , 1393.93454545],
       [ 409.        , 1393.93454545],
       [ 443.        , 1393.93454545],
       [ 459.        , 1393.93454545],
       [ 465.        , 1393.93454545],
       [ 477.        , 1393.93454545],
       [ 480.        , 1393.93454545],
       [ 481.        , 1393.93454545],
       [ 124.        , 1165.        ],
       [ 124.        , 1165.        ],
       [ 124.        , 1165.        ],
       [ 124.        , 11