In [1]:
!cd

C:\Users\admin\Desktop\2021-K-Digital-Training-main\SQL


In [2]:
import pymysql.cursors
import pandas as pd
import numpy as np

In [3]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost', user='root', 
                       password='1281', db='tip', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

    with conn.cursor() as curs:
      sql = "SELECT * FROM tips;"
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
      #df.to_csv('query.csv')

finally:

   conn.close()

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner   2.0
1         10.34  1.66    Male     No  Sun  Dinner   3.0
2         21.01  3.50    Male     No  Sun  Dinner   3.0
3         23.68  3.31    Male     No  Sun  Dinner   2.0
4         24.59  3.61  Female     No  Sun  Dinner   4.0
..          ...   ...     ...    ...  ...     ...   ...
272       20.65  3.35    None     No       Dinner   5.0
273       10.34  1.66    None     No  Sun  Dinner   NaN
274       20.65  3.35    Male     No       Dinner   4.0
275       20.65  3.35    None     No       Dinner   5.0
276       10.34  1.66    None     No  Sun  Dinner   NaN

[277 rows x 7 columns]


In [4]:
df.isnull().sum()

total_bill    0
tip           0
sex           7
smoker        0
day           0
time          0
size          2
dtype: int64

In [5]:
df['sex'].replace({'Female':0, 'Male':1}, inplace=True)
df["smoker"].replace({"No" : 0, "Yes" : 1}, inplace=True)
df["day"].replace({"Thur" : 0, "Fri" : 1, "Sat" : 2, "Sun" : 3}, inplace=True)
df["time"].replace({"Lunch" : 0, "Dinner" : 1}, inplace=True)

In [6]:
df.replace('',np.nan,inplace=True) 

In [7]:
# df = df.drop('day', axis =1)

In [8]:
df.isnull().sum()

total_bill     0
tip            0
sex            7
smoker         0
day           17
time           0
size           2
dtype: int64

In [9]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  277.000000  277.000000  270.000000  277.000000  260.000000  277.000000   
mean    19.474621    2.934585    0.655556    0.335740    1.800000    0.754513   
std      8.532757    1.354212    0.476069    0.473103    1.158484    0.431155   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.280000    2.000000    0.000000    0.000000    1.000000    1.000000   
50%     17.820000    3.000000    1.000000    0.000000    2.000000    1.000000   
75%     22.820000    3.500000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size  
count  275.000000  
mean     2.683636  
std      1.017146  
min      1.000000  
25%      2.000000  
50%      2.000000  
75%      3.000000  
max      6.000000

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
import numpy as np
from sklearn.impute import SimpleImputer

In [12]:
data = df.values

In [13]:
y=df['total_bill'] # 목표변수 total_bill로 설정

In [14]:
X=df.drop('total_bill',axis=1)

In [15]:
X.describe()

tip         sex      smoker         day        time        size
count  277.000000  270.000000  277.000000  260.000000  277.000000  275.000000
mean     2.934585    0.655556    0.335740    1.800000    0.754513    2.683636
std      1.354212    0.476069    0.473103    1.158484    0.431155    1.017146
min      1.000000    0.000000    0.000000    0.000000    0.000000    1.000000
25%      2.000000    0.000000    0.000000    1.000000    1.000000    2.000000
50%      3.000000    1.000000    0.000000    2.000000    1.000000    2.000000
75%      3.500000    1.000000    1.000000    3.000000    1.000000    3.000000
max     10.000000    1.000000    1.000000    3.000000    1.000000    6.000000

In [16]:
y.describe()

count    277.000000
mean      19.474621
std        8.532757
min        3.070000
25%       13.280000
50%       17.820000
75%       22.820000
max       50.810000
Name: total_bill, dtype: float64

In [17]:
data = X.values

In [18]:
y = y.values

In [19]:
data[:,5]

array([ 2.,  3.,  3.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  4.,  2.,
        4.,  2.,  2.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  4.,  2.,  4.,
        2.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,  3.,  3.,  3.,  3.,
        3.,  3.,  2.,  2.,  2.,  4.,  2.,  2.,  4.,  3.,  2.,  2.,  2.,
        4.,  2.,  4.,  2.,  4.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  4.,
        2.,  2.,  2.,  2.,  1.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  3.,  2.,  3.,  2.,  4.,
        2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  6.,  2.,  2.,  2.,  3.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  5.,
        6.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  4.,  4.,  5.,
        6.,  4.,  2.,  4.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  4.,  2.,
        2.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  4

In [20]:
sum(np.isnan(data).flatten())

26

In [21]:
sum(np.isnan(y).flatten())

0

In [22]:
imputer = SimpleImputer(strategy='median')

In [23]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [24]:
data_trans = imputer.transform(data)

In [25]:
# data_trans[:,5]

In [26]:
# df_trans = pd.DataFrame(data_trans)

In [27]:
# df_trans.isnull().sum()

In [28]:
# df_trans

## RFE 

In [29]:
# report which features were selected by RFE

from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVR

In [30]:
estimator = SVR(kernel="linear")

In [31]:
# define RFE
rfe = RFE(estimator, n_features_to_select=4)

In [32]:
# fit RFE
selector=rfe.fit(data_trans, y)

In [33]:
selector.support_

array([ True, False,  True, False,  True,  True])

In [34]:
# summarize all features
for i in range(data_trans.shape[1]):
  print('Column: %d,  Rank: %d' % (i,  rfe.ranking_[i]))

Column: 0,  Rank: 1
Column: 1,  Rank: 2
Column: 2,  Rank: 1
Column: 3,  Rank: 3
Column: 4,  Rank: 1
Column: 5,  Rank: 1


In [35]:
df1=pd.DataFrame(data_trans)
df1

0    1    2    3    4    5
0    1.01  0.0  0.0  3.0  1.0  2.0
1    1.66  1.0  0.0  3.0  1.0  3.0
2    3.50  1.0  0.0  3.0  1.0  3.0
3    3.31  1.0  0.0  3.0  1.0  2.0
4    3.61  0.0  0.0  3.0  1.0  4.0
..    ...  ...  ...  ...  ...  ...
272  3.35  1.0  0.0  2.0  1.0  5.0
273  1.66  1.0  0.0  3.0  1.0  2.0
274  3.35  1.0  0.0  2.0  1.0  4.0
275  3.35  1.0  0.0  2.0  1.0  5.0
276  1.66  1.0  0.0  3.0  1.0  2.0

[277 rows x 6 columns]

In [36]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

## PCA (Principal Component Analysis)

In [37]:
# example of pca for dimensionality reduction
from sklearn.decomposition import PCA

In [38]:
data_trans.shape

(277, 6)

In [39]:
# define the transform
trans = PCA(n_components=4)

In [40]:
# transform the data
X_dim = trans.fit_transform(data_trans)

In [41]:
# summarize data after the transform
print(X_dim[:3, :])

[[-1.71629649 -1.62859846 -0.11385508 -0.67968119]
 [-0.61959243 -1.56128279 -0.71605968  0.02380115]
 [ 0.93063024 -1.04198923  0.11444491 -0.1026397 ]]


## Regression Feature Selection

In [42]:
# pearson's correlation feature selection for numeric input and numeric output
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [43]:
# define feature selection
fs = SelectKBest(score_func=f_regression, k=4)

In [44]:
data_trans.shape

(277, 6)

In [45]:
y.shape

(277,)

In [46]:
# apply feature selection
X_selected = fs.fit_transform(data_trans, y)

In [47]:
print(X_selected.shape)

(277, 4)
